### ISSUE TITLE
fix container size in index.html

### ISSUE THREAD

**Issue by KatiRG** [KatiRG/ExtremeAttributes#20]
The container (or maybe row 2) is too large, causing the footer to be displaced below the field of view.

**Comment by jainak89** [comment]
@KatiRG if you really care, make a call. Stop pretending you care. I won't bother you again and you don't have to wonder what I do or don't do in the future. And thanks for executing your threat.

**Comment by jainak89** [comment]
and you have the guts to lie to the police. Amazing

**Comment by KatiRG** [comment]
<div class="row" style="visibility: hidden"> is not the proper way to hide popup window content from appearing on the main page before the window is clicked open. The recommended way is to initialize the window on $(document).ready(), but with the property autoOpen set to false. Then, on click of the button, call only the window’s open method. This solves the problem of extra row space at the bottom of the page.
